on: push

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: 'Install Dependencies'
        run: |
          bun install --frozen-lockfile
      - name: 'Lint'
        run: |
          bun lint  
      - name: 'Knip'
        run: |
          bun knip 
      - name: 'Check Package'
        run: |
          bun check:package
      - name: 'Check AI Playground'
        run: |
          bun check:ai-playground

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: 'Install Dependencies'
        run: |
          bun install --frozen-lockfile
      - name: 'Test Pokemon'
        run: |
          bun test-pokemon
      - name: 'Test Damage'
        run: |
          bun test-damage
      - name: 'Test AI Playground'
        run: |
          bun test:ai-playground
      - name: 'Install Playwright Chromium'
        run: |
          bun install:e2e-browser
      - name: 'E2E AI Playground'
        run: |
          bun e2e:ai-playground

